# Generated by Django 4.2.7 on 2025-09-10 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_user_remove_passwordresettoken_admin_delete_admin_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
