# Generated by Django 4.2.7 on 2025-09-13 13:46

import cloudinary_storage.storage
from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_delete_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventimage",
            name="is_profile",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="eventvideo",
            name="video",
            field=models.FileField(
                storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(),
                upload_to=events.models.video_upload_to,
            ),
        ),
    ]
